# Generated by pipedat: do not edit by hand
# This file defines the pipeline for the ResearchCompendium project.
library(targets)
library(tarchetypes)
library(pipedat) # To remove by the end of the project

tar_option_set(packages = c('curl', 'googleCloudStorageR', 'aws.s3', 'yaml', 'dplyr'), format = 'file') # To edit properly by the end of the project

tar_source('workspace/scripts/') # To edit properly by the end of the project
list(
  tar_target(bibtex_master, bibtex_master(), format = "file", cue = tar_cue(mode = "always")),
    list(tarchetypes::tar_download(tg_e950ce9d_5743_4901_91bd_a6d7e4a1fd55_Schema_PDF, 
    url = "https://ftp.geogratis.gc.ca/pub/nrcan_rncan/vector/framework_cadre/Atlas_of_Canada_1M/AC_1M_Schema_Dissemination_2017.pdf", 
    path = "workspace/data/harvested/atlas_of_canada_hydrology-1.0.0/raw/AC_1M_Schema_Dissemination_2017.pdf"), 
    tarchetypes::tar_download(tg_e950ce9d_5743_4901_91bd_a6d7e4a1fd55_English_Metadata_PDF, 
        url = "https://ftp.geogratis.gc.ca/pub/nrcan_rncan/vector/framework_cadre/Atlas_of_Canada_1M/AC_1M_metadata_EN_201705.pdf", 
        path = "workspace/data/harvested/atlas_of_canada_hydrology-1.0.0/raw/AC_1M_metadata_EN_201705.pdf"), 
    tarchetypes::tar_download(tg_e950ce9d_5743_4901_91bd_a6d7e4a1fd55_Waterbodies_GDB, 
        url = "https://ftp.geogratis.gc.ca/pub/nrcan_rncan/vector/framework_cadre/Atlas_of_Canada_1M/hydrology/AC_1M_Waterbodies.gdb.zip", 
        path = "workspace/data/harvested/atlas_of_canada_hydrology-1.0.0/raw/AC_1M_Waterbodies.gdb.zip"), 
    tarchetypes::tar_download(tg_e950ce9d_5743_4901_91bd_a6d7e4a1fd55_Rivers_GDB, 
        url = "https://ftp.geogratis.gc.ca/pub/nrcan_rncan/vector/framework_cadre/Atlas_of_Canada_1M/hydrology/AC_1M_Rivers.gdb.zip", 
        path = "workspace/data/harvested/atlas_of_canada_hydrology-1.0.0/raw/AC_1M_Rivers.gdb.zip"), 
    tar_target(tg_e950ce9d_5743_4901_91bd_a6d7e4a1fd55_hydrology, 
        {
            prc_atlas_of_canada_hydrology(output_path = "workspace/data/harvested/atlas_of_canada_hydrology-1.0.0/processed", 
                input_files = list(tg_e950ce9d_5743_4901_91bd_a6d7e4a1fd55_Waterbodies_GDB, 
                  tg_e950ce9d_5743_4901_91bd_a6d7e4a1fd55_Rivers_GDB))
            c("workspace/data/harvested/atlas_of_canada_hydrology-1.0.0/processed/lakes_polygons.gpkg", 
            "workspace/data/harvested/atlas_of_canada_hydrology-1.0.0/processed/lakes_points.gpkg", 
            "workspace/data/harvested/atlas_of_canada_hydrology-1.0.0/processed/rivers_lines.gpkg", 
            "workspace/data/harvested/atlas_of_canada_hydrology-1.0.0/processed/rivers_points.gpkg"
            )
        }, format = "file")),
    list(tar_target(tg_d7a59fef_4cd1_4941_bea6_70d84ae53a5d_canada_outline, 
    {
        prc_canada_outline(output_path = "workspace/data/harvested/canada_outline-1.0.0/processed", 
            input_files = list())
        "workspace/data/harvested/canada_outline-1.0.0/processed/can_1_simplified.gpkg"
    }, format = "file")),
    list(tar_target(tg_e36167b9_1aa9_499b_a242_e9e85b7479cb_FishBase_Freshwater_Species, 
    {
        extract_tables_from_url(urls = "https://www.fishbase.se/country/CountryChecklist.php?what=list&trpp=50&c_code=124&csub_code=&cpresence=present&sortby=alpha2&vhabitat=fresh", 
            next_button_selector = "a:contains('Next')", table_index = 2L, 
            header_contains = NULL, output = "workspace/data/harvested/freshwater_fish_canada-1.0.0/raw/fishbase_freshwater_fish_canada.csv")
        "workspace/data/harvested/freshwater_fish_canada-1.0.0/raw/fishbase_freshwater_fish_canada.csv"
    }, format = "file"), tar_target(tg_e36167b9_1aa9_499b_a242_e9e85b7479cb_FishBase_Species_Status, 
    {
        extract_tables_from_url(urls = "https://www.fishbase.se/country/CountryChecklist.php?what=list&trpp=50&c_code=124&csub_code=&cpresence=present&sortby=alpha2&vhabitat=threatened", 
            next_button_selector = "a:contains('Next')", table_index = 2L, 
            header_contains = NULL, output = "workspace/data/harvested/freshwater_fish_canada-1.0.0/raw/fishbase_fish_status_canada.csv")
        "workspace/data/harvested/freshwater_fish_canada-1.0.0/raw/fishbase_fish_status_canada.csv"
    }, format = "file"), tar_target(tg_e36167b9_1aa9_499b_a242_e9e85b7479cb_FishBase_Game_Species, 
    {
        extract_tables_from_url(urls = "https://www.fishbase.se/country/CountryChecklist.php?what=list&trpp=50&c_code=124&csub_code=&cpresence=present&sortby=alpha2&vhabitat=sports", 
            next_button_selector = "a:contains('Next')", table_index = 2L, 
            header_contains = NULL, output = "workspace/data/harvested/freshwater_fish_canada-1.0.0/raw/fishbase_game_fish_canada.csv")
        "workspace/data/harvested/freshwater_fish_canada-1.0.0/raw/fishbase_game_fish_canada.csv"
    }, format = "file"), tar_target(tg_e36167b9_1aa9_499b_a242_e9e85b7479cb_FishBase_Commercial_Species, 
    {
        extract_tables_from_url(urls = "https://www.fishbase.se/country/CountryChecklist.php?what=list&trpp=50&c_code=124&csub_code=&cpresence=present&sortby=alpha2&vhabitat=commercial", 
            next_button_selector = "a:contains('Next')", table_index = 2L, 
            header_contains = NULL, output = "workspace/data/harvested/freshwater_fish_canada-1.0.0/raw/fishbase_commercial_fish_canada.csv")
        "workspace/data/harvested/freshwater_fish_canada-1.0.0/raw/fishbase_commercial_fish_canada.csv"
    }, format = "file"), tar_target(tg_e36167b9_1aa9_499b_a242_e9e85b7479cb_freshwater_fish_species_canada, 
    {
        prc_freshwater_fish_canada(output_path = "workspace/data/harvested/freshwater_fish_canada-1.0.0/processed", 
            input_files = list(tg_e36167b9_1aa9_499b_a242_e9e85b7479cb_FishBase_Freshwater_Species, 
                tg_e36167b9_1aa9_499b_a242_e9e85b7479cb_FishBase_Species_Status, 
                tg_e36167b9_1aa9_499b_a242_e9e85b7479cb_FishBase_Game_Species, 
                tg_e36167b9_1aa9_499b_a242_e9e85b7479cb_FishBase_Commercial_Species))
        "workspace/data/harvested/freshwater_fish_canada-1.0.0/processed/freshwater_fish_species_canada.csv"
    }, format = "file")),
    list(tar_target(tg_d1c88f68_2fd3_4f3d_afd1_431a4f0630e0_Freshwater_Fish_Species_Occurrences, 
    {
        curl::curl_download("https://figshare.com/ndownloader/files/8964583", 
            "workspace/data/harvested/freshwater_fish_occurrences-1.0.0/raw/freshwater_fish_occurrences.zip")
        "workspace/data/harvested/freshwater_fish_occurrences-1.0.0/raw/freshwater_fish_occurrences.zip"
    }, format = "file"), tar_target(tg_d1c88f68_2fd3_4f3d_afd1_431a4f0630e0_freshwater_fish_occurrences, 
    {
        prc_freshwater_fish_occurrences(output_path = "workspace/data/harvested/freshwater_fish_occurrences-1.0.0/processed", 
            input_files = list(tg_d1c88f68_2fd3_4f3d_afd1_431a4f0630e0_Freshwater_Fish_Species_Occurrences))
        c("workspace/data/harvested/freshwater_fish_occurrences-1.0.0/processed/bassins.gpkg", 
        "workspace/data/harvested/freshwater_fish_occurrences-1.0.0/processed/occurrences.csv"
        )
    }, format = "file")),
    list(list(tar_target(tg_8dac83b6_9c80_4faa_ab5a_8e351d9c55fc_gbif_gcs, 
    {
        googleCloudStorageR::gcs_auth("workspace/credentials/pof-stac-insileco-5d20b0cb59ef.json")
        Sys.setenv(GCS_AUTH_FILE = "workspace/credentials/pof-stac-insileco-5d20b0cb59ef.json")
        googleCloudStorageR::gcs_get_object(object_name = "GBIF/species_occurrences_gbif.gpkg", 
            bucket = "timing-windows", saveToDisk = "workspace/data/harvested/gbif-1.0.0/raw/species_occurrences_gbif.gpkg", 
            overwrite = TRUE)
        "workspace/data/harvested/gbif-1.0.0/raw/species_occurrences_gbif.gpkg"
    }, format = "file"))),
    list(tarchetypes::tar_download(tg_217d3c1a_8b05_499c_8d39_9ad96fe305d9_National_Hydro_Network_GeoBase_GPKG, 
    url = "https://ftp.maps.canada.ca/pub/nrcan_rncan/vector/geobase_nhn_rhn/gpkg_en/CA/rhn_nhn_decoupage.gpkg.zip", 
    path = "workspace/data/harvested/national_hydro_network-1.0.0/raw/rhn_nhn_decoupage.gpkg.zip"), 
    tar_target(tg_217d3c1a_8b05_499c_8d39_9ad96fe305d9_watersheds, 
        {
            prc_national_hydro_network(output_path = "workspace/data/harvested/national_hydro_network-1.0.0/processed", 
                input_files = list(tg_217d3c1a_8b05_499c_8d39_9ad96fe305d9_National_Hydro_Network_GeoBase_GPKG))
            "workspace/data/harvested/national_hydro_network-1.0.0/processed/watersheds.gpkg"
        }, format = "file"))
)
