# Generated by pipedat: do not edit by hand
# This file defines the pipeline for the ResearchCompendium project.
library(targets)
library(tarchetypes)
library(pipedat) # To remove by the end of the project

tar_option_set(packages = c('curl', 'googleCloudStorageR', 'aws.s3', 'yaml', 'dplyr'), format = 'file') # To edit properly by the end of the project

tar_source('workspace/scripts/') # To edit properly by the end of the project
list(
  tar_target(bibtex_master, bibtex_master(), format = "file", cue = tar_cue(mode = "always")),
    list(tarchetypes::tar_download(tg_e950ce9d_5743_4901_91bd_a6d7e4a1fd55_Schema_PDF, 
    url = "https://ftp.geogratis.gc.ca/pub/nrcan_rncan/vector/framework_cadre/Atlas_of_Canada_1M/AC_1M_Schema_Dissemination_2017.pdf", 
    path = "workspace/data/harvested/atlas_of_canada_hydrology-1.0.0/raw/AC_1M_Schema_Dissemination_2017.pdf"), 
    tarchetypes::tar_download(tg_e950ce9d_5743_4901_91bd_a6d7e4a1fd55_English_Metadata_PDF, 
        url = "https://ftp.geogratis.gc.ca/pub/nrcan_rncan/vector/framework_cadre/Atlas_of_Canada_1M/AC_1M_metadata_EN_201705.pdf", 
        path = "workspace/data/harvested/atlas_of_canada_hydrology-1.0.0/raw/AC_1M_metadata_EN_201705.pdf"), 
    tarchetypes::tar_download(tg_e950ce9d_5743_4901_91bd_a6d7e4a1fd55_Waterbodies_GDB, 
        url = "https://ftp.geogratis.gc.ca/pub/nrcan_rncan/vector/framework_cadre/Atlas_of_Canada_1M/hydrology/AC_1M_Waterbodies.gdb.zip", 
        path = "workspace/data/harvested/atlas_of_canada_hydrology-1.0.0/raw/AC_1M_Waterbodies.gdb.zip"), 
    tarchetypes::tar_download(tg_e950ce9d_5743_4901_91bd_a6d7e4a1fd55_Rivers_GDB, 
        url = "https://ftp.geogratis.gc.ca/pub/nrcan_rncan/vector/framework_cadre/Atlas_of_Canada_1M/hydrology/AC_1M_Rivers.gdb.zip", 
        path = "workspace/data/harvested/atlas_of_canada_hydrology-1.0.0/raw/AC_1M_Rivers.gdb.zip"), 
    tar_target(tg_e950ce9d_5743_4901_91bd_a6d7e4a1fd55_hydrology, 
        {
            prc_atlas_of_canada_hydrology(output_path = "workspace/data/harvested/atlas_of_canada_hydrology-1.0.0/processed", 
                input_files = list(tg_e950ce9d_5743_4901_91bd_a6d7e4a1fd55_Waterbodies_GDB, 
                  tg_e950ce9d_5743_4901_91bd_a6d7e4a1fd55_Rivers_GDB))
            c("workspace/data/harvested/atlas_of_canada_hydrology-1.0.0/processed/lakes_polygons.gpkg", 
            "workspace/data/harvested/atlas_of_canada_hydrology-1.0.0/processed/lakes_points.gpkg", 
            "workspace/data/harvested/atlas_of_canada_hydrology-1.0.0/processed/rivers_lines.gpkg", 
            "workspace/data/harvested/atlas_of_canada_hydrology-1.0.0/processed/rivers_points.gpkg"
            )
        }, format = "file")),
    list(tar_target(tg_d7a59fef_4cd1_4941_bea6_70d84ae53a5d_canada_outline, 
    {
        prc_canada_outline(output_path = "workspace/data/harvested/canada_outline-1.0.0/processed", 
            input_files = list())
        "workspace/data/harvested/canada_outline-1.0.0/processed/can_1_simplified.gpkg"
    }, format = "file")),
    list(tarchetypes::tar_download(tg_c54f4d0a_9b58_444d_9afe_90ea795cb212_Experimental_and_Imputed_Tolerance_Data, 
    url = "https://store.pangaea.de/Publications/DahlkeF-etal_2020/Experimental_and_imputed_tolerance_data.xlsx", 
    path = "workspace/data/harvested/dahlke_2020-1.0.0/raw/experimental_and_imputed_tolerance_data.xlsx"), 
    tarchetypes::tar_download(tg_c54f4d0a_9b58_444d_9afe_90ea795cb212_Thermal_Safety_Margins, 
        url = "https://store.pangaea.de/Publications/DahlkeF-etal_2020/Thermal_Safety_Margins.xlsx", 
        path = "workspace/data/harvested/dahlke_2020-1.0.0/raw/thermal_safety_margins.xlsx"), 
    tarchetypes::tar_download(tg_c54f4d0a_9b58_444d_9afe_90ea795cb212_Thermal_Responsiveness, 
        url = "https://store.pangaea.de/Publications/DahlkeF-etal_2020/Thermal_responsiveness.xlsx", 
        path = "workspace/data/harvested/dahlke_2020-1.0.0/raw/thermal_responsiveness.xlsx"), 
    tarchetypes::tar_download(tg_c54f4d0a_9b58_444d_9afe_90ea795cb212_Thermal_Tolerance, 
        url = "https://store.pangaea.de/Publications/DahlkeF-etal_2020/Thermal_tolerance.xlsx", 
        path = "workspace/data/harvested/dahlke_2020-1.0.0/raw/thermal_tolerance.xlsx"), 
    tar_target(tg_c54f4d0a_9b58_444d_9afe_90ea795cb212_dahlke_processed, 
        {
            prc_dahlke_2020(output_path = "workspace/data/harvested/dahlke_2020-1.0.0/processed", 
                input_files = list(tg_c54f4d0a_9b58_444d_9afe_90ea795cb212_Experimental_and_Imputed_Tolerance_Data, 
                  tg_c54f4d0a_9b58_444d_9afe_90ea795cb212_Thermal_Safety_Margins, 
                  tg_c54f4d0a_9b58_444d_9afe_90ea795cb212_Thermal_Responsiveness, 
                  tg_c54f4d0a_9b58_444d_9afe_90ea795cb212_Thermal_Tolerance))
            c("workspace/data/harvested/dahlke_2020-1.0.0/processed/experimental_imputed_tolerance.csv", 
            "workspace/data/harvested/dahlke_2020-1.0.0/processed/thermal_safety_margins.csv", 
            "workspace/data/harvested/dahlke_2020-1.0.0/processed/thermal_responsiveness.csv", 
            "workspace/data/harvested/dahlke_2020-1.0.0/processed/thermal_tolerance.csv"
            )
        }, format = "file")),
    list(tar_target(tg_44238b88_cc41_4468_b1fc_7b770c4a4be4_FishPass_database, 
    {
        curl::curl_download("https://datadryad.org/api/v2/datasets/doi%3A10.5061%2Fdryad.fqz612jwj/download", 
            "workspace/data/harvested/fishpass-1.0.0/raw/FishPass_Database.zip")
        "workspace/data/harvested/fishpass-1.0.0/raw/FishPass_Database.zip"
    }, format = "file"), tar_target(tg_44238b88_cc41_4468_b1fc_7b770c4a4be4_FishPass_processed, 
    {
        prc_fishpass(output_path = "workspace/data/harvested/fishpass-1.0.0/processed", 
            input_files = list(tg_44238b88_cc41_4468_b1fc_7b770c4a4be4_FishPass_database))
        c("workspace/data/harvested/fishpass-1.0.0/processed/fishpass_behaviour.csv", 
        "workspace/data/harvested/fishpass-1.0.0/processed/fishpass_morphology.csv", 
        "workspace/data/harvested/fishpass-1.0.0/processed/fishpass_phenology.csv", 
        "workspace/data/harvested/fishpass-1.0.0/processed/fishpass_physiology.csv"
        )
    }, format = "file")),
    list(tar_target(tg_e36167b9_1aa9_499b_a242_e9e85b7479cb_FishBase_Freshwater_Species, 
    {
        extract_tables_from_url(urls = "https://www.fishbase.se/country/CountryChecklist.php?what=list&trpp=50&c_code=124&csub_code=&cpresence=present&sortby=alpha2&vhabitat=fresh", 
            next_button_selector = "a:contains('Next')", table_index = 2L, 
            header_contains = NULL, output = "workspace/data/harvested/freshwater_fish_canada-1.0.0/raw/fishbase_freshwater_fish_canada.csv")
        "workspace/data/harvested/freshwater_fish_canada-1.0.0/raw/fishbase_freshwater_fish_canada.csv"
    }, format = "file"), tar_target(tg_e36167b9_1aa9_499b_a242_e9e85b7479cb_FishBase_Species_Status, 
    {
        extract_tables_from_url(urls = "https://www.fishbase.se/country/CountryChecklist.php?what=list&trpp=50&c_code=124&csub_code=&cpresence=present&sortby=alpha2&vhabitat=threatened", 
            next_button_selector = "a:contains('Next')", table_index = 2L, 
            header_contains = NULL, output = "workspace/data/harvested/freshwater_fish_canada-1.0.0/raw/fishbase_fish_status_canada.csv")
        "workspace/data/harvested/freshwater_fish_canada-1.0.0/raw/fishbase_fish_status_canada.csv"
    }, format = "file"), tar_target(tg_e36167b9_1aa9_499b_a242_e9e85b7479cb_FishBase_Game_Species, 
    {
        extract_tables_from_url(urls = "https://www.fishbase.se/country/CountryChecklist.php?what=list&trpp=50&c_code=124&csub_code=&cpresence=present&sortby=alpha2&vhabitat=sports", 
            next_button_selector = "a:contains('Next')", table_index = 2L, 
            header_contains = NULL, output = "workspace/data/harvested/freshwater_fish_canada-1.0.0/raw/fishbase_game_fish_canada.csv")
        "workspace/data/harvested/freshwater_fish_canada-1.0.0/raw/fishbase_game_fish_canada.csv"
    }, format = "file"), tar_target(tg_e36167b9_1aa9_499b_a242_e9e85b7479cb_FishBase_Commercial_Species, 
    {
        extract_tables_from_url(urls = "https://www.fishbase.se/country/CountryChecklist.php?what=list&trpp=50&c_code=124&csub_code=&cpresence=present&sortby=alpha2&vhabitat=commercial", 
            next_button_selector = "a:contains('Next')", table_index = 2L, 
            header_contains = NULL, output = "workspace/data/harvested/freshwater_fish_canada-1.0.0/raw/fishbase_commercial_fish_canada.csv")
        "workspace/data/harvested/freshwater_fish_canada-1.0.0/raw/fishbase_commercial_fish_canada.csv"
    }, format = "file"), tar_target(tg_e36167b9_1aa9_499b_a242_e9e85b7479cb_freshwater_fish_species_canada, 
    {
        prc_freshwater_fish_canada(output_path = "workspace/data/harvested/freshwater_fish_canada-1.0.0/processed", 
            input_files = list(tg_e36167b9_1aa9_499b_a242_e9e85b7479cb_FishBase_Freshwater_Species, 
                tg_e36167b9_1aa9_499b_a242_e9e85b7479cb_FishBase_Species_Status, 
                tg_e36167b9_1aa9_499b_a242_e9e85b7479cb_FishBase_Game_Species, 
                tg_e36167b9_1aa9_499b_a242_e9e85b7479cb_FishBase_Commercial_Species))
        "workspace/data/harvested/freshwater_fish_canada-1.0.0/processed/freshwater_fish_species_canada.csv"
    }, format = "file")),
    list(tar_target(tg_d1c88f68_2fd3_4f3d_afd1_431a4f0630e0_Freshwater_Fish_Species_Occurrences, 
    {
        curl::curl_download("https://figshare.com/ndownloader/files/8964583", 
            "workspace/data/harvested/freshwater_fish_occurrences-1.0.0/raw/freshwater_fish_occurrences.zip")
        "workspace/data/harvested/freshwater_fish_occurrences-1.0.0/raw/freshwater_fish_occurrences.zip"
    }, format = "file"), tar_target(tg_d1c88f68_2fd3_4f3d_afd1_431a4f0630e0_freshwater_fish_occurrences, 
    {
        prc_freshwater_fish_occurrences(output_path = "workspace/data/harvested/freshwater_fish_occurrences-1.0.0/processed", 
            input_files = list(tg_d1c88f68_2fd3_4f3d_afd1_431a4f0630e0_Freshwater_Fish_Species_Occurrences))
        c("workspace/data/harvested/freshwater_fish_occurrences-1.0.0/processed/bassins.gpkg", 
        "workspace/data/harvested/freshwater_fish_occurrences-1.0.0/processed/occurrences.csv"
        )
    }, format = "file")),
    list(list(tar_target(tg_8dac83b6_9c80_4faa_ab5a_8e351d9c55fc_gbif_gcs, 
    {
        googleCloudStorageR::gcs_auth("workspace/credentials/pof-stac-insileco-5d20b0cb59ef.json")
        Sys.setenv(GCS_AUTH_FILE = "workspace/credentials/pof-stac-insileco-5d20b0cb59ef.json")
        googleCloudStorageR::gcs_get_object(object_name = "GBIF/species_occurrences_gbif.gpkg", 
            bucket = "timing-windows", saveToDisk = "workspace/data/harvested/gbif-1.0.0/raw/species_occurrences_gbif.gpkg", 
            overwrite = TRUE)
        "workspace/data/harvested/gbif-1.0.0/raw/species_occurrences_gbif.gpkg"
    }, format = "file"))),
    list(tarchetypes::tar_download(tg_217d3c1a_8b05_499c_8d39_9ad96fe305d9_National_Hydro_Network_GeoBase_GPKG, 
    url = "https://ftp.maps.canada.ca/pub/nrcan_rncan/vector/geobase_nhn_rhn/gpkg_en/CA/rhn_nhn_decoupage.gpkg.zip", 
    path = "workspace/data/harvested/national_hydro_network-1.0.0/raw/rhn_nhn_decoupage.gpkg.zip"), 
    tar_target(tg_217d3c1a_8b05_499c_8d39_9ad96fe305d9_watersheds, 
        {
            prc_national_hydro_network(output_path = "workspace/data/harvested/national_hydro_network-1.0.0/processed", 
                input_files = list(tg_217d3c1a_8b05_499c_8d39_9ad96fe305d9_National_Hydro_Network_GeoBase_GPKG))
            "workspace/data/harvested/national_hydro_network-1.0.0/processed/watersheds.gpkg"
        }, format = "file")),
    list(tar_target(tg_0fedf29b_2fe3_49cc_b2b5_d1ebd3b8af2b_NAFMFD_Data, 
    {
        curl::curl_download("https://www.sciencebase.gov/catalog/file/get/619d2dbcd34eb622f6951e8a?name=NAFMFD_finalcopy.xlsx", 
            "workspace/data/harvested/north_american_freshwater_migratory_fish_database-1.0.0/raw/NAFMFD_finalcopy.xlsx")
        "workspace/data/harvested/north_american_freshwater_migratory_fish_database-1.0.0/raw/NAFMFD_finalcopy.xlsx"
    }, format = "file"), tar_target(tg_0fedf29b_2fe3_49cc_b2b5_d1ebd3b8af2b_NAFMFD_Metadata, 
    {
        curl::curl_download("https://www.sciencebase.gov/catalog/file/get/619d2dbcd34eb622f6951e8a?name=NAFMFD_metadata_12-20-2021.xml", 
            "workspace/data/harvested/north_american_freshwater_migratory_fish_database-1.0.0/raw/NAFMFD_metadata_12-20-2021.xml")
        "workspace/data/harvested/north_american_freshwater_migratory_fish_database-1.0.0/raw/NAFMFD_metadata_12-20-2021.xml"
    }, format = "file"), tar_target(tg_0fedf29b_2fe3_49cc_b2b5_d1ebd3b8af2b_NAFMFD_processed, 
    {
        prc_north_american_freshwater_migratory_fish_database(output_path = "workspace/data/harvested/north_american_freshwater_migratory_fish_database-1.0.0/processed", 
            input_files = list(tg_0fedf29b_2fe3_49cc_b2b5_d1ebd3b8af2b_NAFMFD_Data))
        "workspace/data/harvested/north_american_freshwater_migratory_fish_database-1.0.0/processed/north_american_freshwater_migratory_fish_database.csv"
    }, format = "file")),
    list(tar_target(tg_1a084fb5_2dbd_4df9_9543_e020ec0ee77a_Ontario_Freshwater_Fishes_Life_History_Database, 
    {
        dwn_ontario_freshwater_fishes_life_history(output_path = "workspace/data/harvested/ontario_freshwater_fishes_life_history-1.0.0/processed", 
            input_files = list())
        c("workspace/data/harvested/ontario_freshwater_fishes_life_history-1.0.0/processed/ontario_fishes_characteristics.csv", 
        "workspace/data/harvested/ontario_freshwater_fishes_life_history-1.0.0/processed/ontario_fishes_references.csv"
        )
    }, format = "file")),
    list(list(tar_target(tg_d56fc2b3_318b_489a_8000_54501f7ae5e7_Roberge_Dataset, 
    {
        googleCloudStorageR::gcs_auth("workspace/credentials/pof-stac-insileco-5d20b0cb59ef.json")
        Sys.setenv(GCS_AUTH_FILE = "workspace/credentials/pof-stac-insileco-5d20b0cb59ef.json")
        googleCloudStorageR::gcs_get_object(object_name = "roberge2002/Roberge2002.txt", 
            bucket = "timing-windows", saveToDisk = "workspace/data/harvested/roberge_2002-1.0.0/raw/Roberge2002.txt", 
            overwrite = TRUE)
        "workspace/data/harvested/roberge_2002-1.0.0/raw/Roberge2002.txt"
    }, format = "file")), list(tar_target(tg_d56fc2b3_318b_489a_8000_54501f7ae5e7_Roberge_Report, 
    {
        googleCloudStorageR::gcs_auth("workspace/credentials/pof-stac-insileco-5d20b0cb59ef.json")
        Sys.setenv(GCS_AUTH_FILE = "workspace/credentials/pof-stac-insileco-5d20b0cb59ef.json")
        googleCloudStorageR::gcs_get_object(object_name = "roberge2002/Fs97-4-2611E.pdf", 
            bucket = "timing-windows", saveToDisk = "workspace/data/harvested/roberge_2002-1.0.0/raw/Fs97-4-2611E.pdf", 
            overwrite = TRUE)
        "workspace/data/harvested/roberge_2002-1.0.0/raw/Fs97-4-2611E.pdf"
    }, format = "file")), tar_target(tg_d56fc2b3_318b_489a_8000_54501f7ae5e7_roberge_processed, 
    {
        prc_roberge_2002(output_path = "workspace/data/harvested/roberge_2002-1.0.0/processed", 
            input_files = list(tg_d56fc2b3_318b_489a_8000_54501f7ae5e7_Roberge_Dataset))
        "workspace/data/harvested/roberge_2002-1.0.0/processed/roberge.csv"
    }, format = "file")),
    list(tar_target(tg_bf63ff45_6283_4bdc_b360_746549ee32ed_download_fishbase, 
    {
        download_fishbase(output_path = "workspace/data/analyzed/fishbase-1.0.0", 
            input_files = list(tg_e36167b9_1aa9_499b_a242_e9e85b7479cb_freshwater_fish_species_canada))
        c("workspace/data/analyzed/fishbase-1.0.0/ecology.csv", 
        "workspace/data/analyzed/fishbase-1.0.0/eggdev.csv", 
        "workspace/data/analyzed/fishbase-1.0.0/fecundity.csv", 
        "workspace/data/analyzed/fishbase-1.0.0/fooditems.csv", 
        "workspace/data/analyzed/fishbase-1.0.0/larvae_phenology.csv", 
        "workspace/data/analyzed/fishbase-1.0.0/larvae_traits.csv", 
        "workspace/data/analyzed/fishbase-1.0.0/larvaepresence_phenology.csv", 
        "workspace/data/analyzed/fishbase-1.0.0/larvdyn.csv", 
        "workspace/data/analyzed/fishbase-1.0.0/reproduc.csv", 
        "workspace/data/analyzed/fishbase-1.0.0/spawning_phenology.csv", 
        "workspace/data/analyzed/fishbase-1.0.0/spawning_traits.csv", 
        "workspace/data/analyzed/fishbase-1.0.0/species.csv", 
        "workspace/data/analyzed/fishbase-1.0.0/swimming.csv"
        )
    }, format = "file")),
    list(tar_target(tg_47a31643_e5a1_4126_9070_909f742c85cd_national_timing_windows_database, 
    {
        int_national_timing_windows_dataset(output_path = "workspace/data/analyzed/national_timing_windows_dataset-1.0.0", 
            input_files = list(tg_e36167b9_1aa9_499b_a242_e9e85b7479cb_freshwater_fish_species_canada, 
                tg_e950ce9d_5743_4901_91bd_a6d7e4a1fd55_hydrology, 
                tg_217d3c1a_8b05_499c_8d39_9ad96fe305d9_watersheds, 
                tg_4e7387b0_19f5_4951_8dac_6215e3224144_waterbodies_and_species_intersect, 
                tg_867509cc_57d1_4be5_9750_ab397153a7ee_watersheds_and_species_intersect))
        c("workspace/data/analyzed/national_timing_windows_dataset-1.0.0/national_timing_windows_database.sqlite", 
        "workspace/data/analyzed/national_timing_windows_dataset-1.0.0/national_timing_windows_database.svg"
        )
    }, format = "file")),
    list(tar_target(tg_b4f3f034_0ff5_4cf8_aa92_aa897a86a723_integrate_species_phenology, 
    {
        ana_species_phenology(output_path = "workspace/data/analyzed/species_phenology-1.0.0", 
            input_files = list(tg_e36167b9_1aa9_499b_a242_e9e85b7479cb_freshwater_fish_species_canada, 
                tg_c54f4d0a_9b58_444d_9afe_90ea795cb212_dahlke_processed, 
                tg_bf63ff45_6283_4bdc_b360_746549ee32ed_download_fishbase, 
                tg_44238b88_cc41_4468_b1fc_7b770c4a4be4_FishPass_processed, 
                tg_0fedf29b_2fe3_49cc_b2b5_d1ebd3b8af2b_NAFMFD_processed, 
                tg_1a084fb5_2dbd_4df9_9543_e020ec0ee77a_Ontario_Freshwater_Fishes_Life_History_Database, 
                tg_d56fc2b3_318b_489a_8000_54501f7ae5e7_roberge_processed, 
                tg_e53aa36a_6191_497b_ad1b_4e55159d0774_integrate_species_traits))
        c("workspace/data/analyzed/species_phenology-1.0.0/spawning.csv", 
        "workspace/data/analyzed/species_phenology-1.0.0/migration.csv", 
        "workspace/data/analyzed/species_phenology-1.0.0/larvae.csv"
        )
    }, format = "file")),
    list(tar_target(tg_e53aa36a_6191_497b_ad1b_4e55159d0774_integrate_species_traits, 
    {
        ana_species_traits(output_path = "workspace/data/analyzed/species_traits-1.0.0", 
            input_files = list(tg_e36167b9_1aa9_499b_a242_e9e85b7479cb_freshwater_fish_species_canada, 
                tg_c54f4d0a_9b58_444d_9afe_90ea795cb212_dahlke_processed, 
                tg_bf63ff45_6283_4bdc_b360_746549ee32ed_download_fishbase, 
                tg_44238b88_cc41_4468_b1fc_7b770c4a4be4_FishPass_processed, 
                tg_0fedf29b_2fe3_49cc_b2b5_d1ebd3b8af2b_NAFMFD_processed, 
                tg_1a084fb5_2dbd_4df9_9543_e020ec0ee77a_Ontario_Freshwater_Fishes_Life_History_Database, 
                tg_d56fc2b3_318b_489a_8000_54501f7ae5e7_roberge_processed))
        c("workspace/data/analyzed/species_traits-1.0.0/habitat_adult.csv", 
        "workspace/data/analyzed/species_traits-1.0.0/habitat_juvenile.csv", 
        "workspace/data/analyzed/species_traits-1.0.0/habitat_spawning.csv", 
        "workspace/data/analyzed/species_traits-1.0.0/habitat_yoy.csv", 
        "workspace/data/analyzed/species_traits-1.0.0/food_items.csv", 
        "workspace/data/analyzed/species_traits-1.0.0/spawning.csv", 
        "workspace/data/analyzed/species_traits-1.0.0/eggs.csv", 
        "workspace/data/analyzed/species_traits-1.0.0/larvae.csv", 
        "workspace/data/analyzed/species_traits-1.0.0/migration.csv", 
        "workspace/data/analyzed/species_traits-1.0.0/morphology.csv", 
        "workspace/data/analyzed/species_traits-1.0.0/tolerance_adult.csv", 
        "workspace/data/analyzed/species_traits-1.0.0/tolerance_embryo.csv", 
        "workspace/data/analyzed/species_traits-1.0.0/tolerance_larvae.csv", 
        "workspace/data/analyzed/species_traits-1.0.0/tolerance_spawner.csv", 
        "workspace/data/analyzed/species_traits-1.0.0/taxonomy.csv", 
        "workspace/data/analyzed/species_traits-1.0.0/picture.csv", 
        "workspace/data/analyzed/species_traits-1.0.0/swimming.csv"
        )
    }, format = "file")),
    list(tar_target(tg_4e7387b0_19f5_4951_8dac_6215e3224144_waterbodies_and_species_intersect, 
    {
        ana_waterbodies_species(output_path = "workspace/data/analyzed/waterbodies_species-1.0.0", 
            input_files = list(tg_e36167b9_1aa9_499b_a242_e9e85b7479cb_freshwater_fish_species_canada, 
                tg_e950ce9d_5743_4901_91bd_a6d7e4a1fd55_hydrology, 
                tg_8dac83b6_9c80_4faa_ab5a_8e351d9c55fc_gbif_gcs))
        "workspace/data/analyzed/waterbodies_species-1.0.0/waterbodies_species.csv"
    }, format = "file")),
    list(tar_target(tg_867509cc_57d1_4be5_9750_ab397153a7ee_watersheds_and_species_intersect, 
    {
        ana_watersheds_species(output_path = "workspace/data/analyzed/watersheds_species-1.0.0", 
            input_files = list(tg_e36167b9_1aa9_499b_a242_e9e85b7479cb_freshwater_fish_species_canada, 
                tg_217d3c1a_8b05_499c_8d39_9ad96fe305d9_watersheds, 
                tg_8dac83b6_9c80_4faa_ab5a_8e351d9c55fc_gbif_gcs))
        "workspace/data/analyzed/watersheds_species-1.0.0/watersheds_species.csv"
    }, format = "file"))
)
