pipeline:
  id: d7a59fef-4cd1-4941-bea6-70d84ae53a5d
  name: canada_outline
  version: 1.0.0
  package_version: 0.0.0.9001
  created_at: 2025-01-22 15:15:40
  last_modified: 2025-01-22 15:15:40
  description: "This pipeline creates a simplified polygon of the outline of Canada."

  # Metadata section providing details about the analysis
  metadata:
    source_name: "Canada outline"    # Name of the analysis
    data_type: "GeoPackage"              # Types of output data
    file_size: "Variable"                           # Size depends on the study area
    license: "Internal Use Only"                    # License for the outputs
    last_updated: "2025-01-22"                      # Date of creation
    geographic_coverage:                            # Geographical region covered by the AOI
      region: "Study Area"
    temporal_coverage:                              # Not applicable for static AOI
      start_date: null
      end_date: null
    variables:                                      # Outputs include spatial variables
      - canada_outline

  bibliography:
    - "@TechReport{gadm2023,
        title = {GADM Database of Global Administrative Areas, version 4.1},
        author = {GADM (Database of Global Administrative Areas},
        year = {2023},
        institution = {GADM},
        url = {https://gadm.org},
      }"

  # Processing section: Define the analysis step
  processing:
    sources:
      - name: canada outline
        script: prc_canada_outline
        input_files: []
        output_files:
          - can_1_simplified.gpkg

  # Output section: final output of the processed data
  output:
    output_dir: "workspace/data/analyzed/"         # Base directory for the generated data
    log_dir: "workspace/logs/"                     # Directory for logs (optional)
    archive_raw: false                             # No raw data to archive for this analysis
