pipeline:
  id: 867509cc-57d1-4be5-9750-ab397153a7ee
  name: watersheds_species
  version: 1.0.0
  package_version: 0.0.0.9001
  created_at: 2025-01-23 16:43:23
  last_modified: 2025-01-23 16:43:23
  description: "This analytical pipeline intersects species occurrence records from the GBIF dataset with geospatial data on watersheds from the National Hydro Network. The goal is to identify which species have been observed in specific watersheds across Canada."

  analysis:
    sources:
      - name: watersheds and species intersect
        description: spatial intersections between species and watersheds
        script: ana_watersheds_species
        input_files:
        - id: e36167b9-1aa9-499b-a242-e9e85b7479cb
          name: freshwater fish species canada
        - id: 217d3c1a-8b05-499c-8d39-9ad96fe305d9
          name: watersheds
        - id: 8dac83b6-9c80-4faa-ab5a-8e351d9c55fc
          name: gbif gcs
        output_files:
          - watersheds_species.csv

  output:
    output_dir: "workspace/data/analyzed/watersheds_species/"
    log_dir: "workspace/logs/"
    archive_raw: false
