project:
  type: book
  output-dir: ../../docs

book:
  title: National Timing Windows Dataset
  subtitle: Presentation of datasets
  author: 
    - name: David Beauchesne
      degrees: PhD
    - name: Kevin Cazelles
      degrees: PhD
  chapters:
    - index.qmd
    - 1_research_compendium.qmd
    - 2_data.qmd
    - 3_national_dataset.qmd

bibliography: [references.bib, ../../workspace/bibliographies/data.bib]
csl: frontiers.csl

format:
  html:
    theme: cosmo

execute:
  echo: false
  warning: false
  error: false