project:
  type: book
  output-dir: ../../docs

book:
  title: Mapping threats at sea to marine birds throughout their annual cycle to inform conservation and management in Atlantic Canada
  subtitle: Progress report
  author: 
    - name: David Beauchesne
      degrees: PhD
    - name: Kevin Cazelles
      degrees: PhD
    - name: Steve Vissault
      degrees: MSc
  chapters:
    - index.qmd
    - 1_research_compendium.qmd
    - 2_data.qmd
    - 3_threats.qmd

bibliography: [references.bib, ../../workspace/bibliographies/data.bib]
csl: frontiers.csl

format:
  html:
    theme: cosmo

execute:
  echo: false
  warning: false
  error: false